### ISSUE TITLE
 black screen show (remote-video)

### ISSUE THREAD

**Issue by ashish1409** [Terkea/fireReactRTC#2]
Hi Terkea,
  i have clone your project and setup firebase as per instruction of you. but after run app remort video screen is black, can you help me out for this , console also show the message 
Join room:  AIFqSnthQDDyRs6iYEIY
App.js:108 Got room: true

my window Google Chrome:-
Version 83.0.4103.106 (Official Build) (64-bit)

[screencapture-localhost-3000-2020-06-17-21_36_06.pdf](https://github.com/Terkea/fireReactRTC/files/4793834/screencapture-localhost-3000-2020-06-17-21_36_06.pdf)

**Comment by Terkea** [comment]
I just realized now after reading your question that in order to access the room is best to join it from a separate browser tab otherwise, indeed the black screen would occur and for some reason, you have to hit the join button twice

https://youtu.be/A7hA5v7i9og

**Comment by ashish1409** [comment]
Thanks for reply , minor mistake from my side

**Comment by ashish1409** [comment]
> Hi Terkea,
> i have clone your project and setup firebase as per instruction of you. but after run app remort video screen is black, can you help me out for this , console also show the message
> Join room: AIFqSnthQDDyRs6iYEIY
> App.js:108 Got room: true
> 
> my window Google Chrome:-
> Version 83.0.4103.106 (Official Build) (64-bit)
> 
> [screencapture-localhost-3000-2020-06-17-21_36_06.pdf](https://github.com/Terkea/fireReactRTC/files/4793834/screencapture-localhost-3000-2020-06-17-21_36_06.pdf)
